# Generated by Django 2.1.7 on 2019-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20190401_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('started_on', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('reward_st', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InterestingThoughts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField()),
                ('reward_st', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewThings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('executed_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('reward_st', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField()),
                ('reward_st', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='element',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='element',
            name='email',
        ),
        migrations.AddField(
            model_name='element',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
