# Generated by Django 2.1.7 on 2019-04-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20190406_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestingThoughts',
            new_name='InterestingThought',
        ),
        migrations.RenameModel(
            old_name='NewThings',
            new_name='NewThing',
        ),
    ]
